load("@rules_cc//cc:defs.bzl", "cc_library", "cc_binary", "cc_import")

cc_binary(
    name = "simple-integers-serial-bgvrns",
    srcs = ["simple-integers-serial-bgvrns.cc"],
    deps = ["@openfhe//:pke"],
)
